import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';

for (const viewport of [{ width: 375, height: 812 }, { width: 1440, height: 900 }]) {
  test(`ACT reference convention renders consistently at ${viewport.width}`, async ({ page }, testInfo) => {
    test.setTimeout(120_000);
    const dir = process.env.ACT_CORRECTION_EVIDENCE_DIR ?? testInfo.outputPath('act');
    mkdirSync(dir, { recursive: true });
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.setViewportSize(viewport);
    await page.goto('/manipulation/action-chunking/');
    await page.evaluate(() => document.fonts.ready);
    await page.waitForLoadState('networkidle');
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('Action Chunking (ACT and ALOHA)');
    await page.screenshot({ caret: 'initial', path: join(dir, `act-${viewport.width}-top.png`) });
    const hardware = page.locator('p').filter({ hasText: 'The 14 action coordinates are' });
    await expect(hardware).toContainText('six arm joints and one gripper coordinate per arm');
    await expect(hardware).toContainText('7+7=14 DoF');
    await hardware.scrollIntoViewIfNeeded();
    await page.screenshot({ caret: 'initial', path: join(dir, `act-${viewport.width}-hardware-loss.png`) });
    const loss = page.locator('p').filter({ hasText: 'The objective in the card follows' });
    await expect(loss).toContainText('Section IV-C specifies L1 reconstruction');
    await expect(loss).toContainText('Algorithm 1 prints MSE');
    await expect(loss).toContainText('not a universal ACT objective');
    await loss.screenshot({ caret: 'initial', path: join(dir, `act-${viewport.width}-loss-conflict.png`) });
    const heading = page.getByRole('heading', { name: 'Temporal ensembling and its limits', exact: true });
    await heading.scrollIntoViewIfNeeded();
    const image = page.locator('img[src*="temporal-ensembling.svg"]');
    await expect(image).toHaveAttribute('alt', /oldest-to-newest unnormalized weights are 1.00, 0.61, and 0.37/);
    const figure = image.locator('xpath=ancestor::figure');
    await expect(figure).toContainText('oldest gets the largest weight');
    await expect(figure).toContainText('m=0.01, not 0.5');
    await expect(figure.getByRole('link', { name: /CC BY 4.0/ })).toHaveAttribute('href', 'https://creativecommons.org/licenses/by/4.0');
    const response = await page.request.get('/images/temporal-ensembling.svg');
    expect(response.status()).toBe(200);
    const svg = await response.body();
    const source = readFileSync('public/images/temporal-ensembling.svg');
    expect(svg.equals(source)).toBe(true);
    await figure.screenshot({ caret: 'initial', path: join(dir, `act-${viewport.width}-figure.png`) });
    const paragraph = page.locator('p').filter({ hasText: 'The pinned ACT reference implementation uses' });
    await expect(paragraph).toContainText('oldest retained prediction has the largest weight');
    expect(await paragraph.locator('.katex').count()).toBe(4);
    await paragraph.scrollIntoViewIfNeeded();
    await page.screenshot({ caret: 'initial', path: join(dir, `act-${viewport.width}-convention.png`) });
    const term = page.locator('[data-term-id="temporal-ensembling"]');
    await term.getByRole('link').focus();
    await expect(term.getByRole('tooltip')).toContainText('oldest retained prediction has the largest weight');
    const tip = await term.getByRole('tooltip').boundingBox();
    expect(tip).not.toBeNull();
    expect(tip!.x).toBeGreaterThanOrEqual(0);
    expect(tip!.x + tip!.width).toBeLessThanOrEqual(viewport.width);
    await page.screenshot({ caret: 'initial', path: join(dir, `act-${viewport.width}-glossary.png`) });
    const cite = page.locator('[data-cite-id="act-reference-2023"] a').first();
    await cite.focus();
    await expect(cite).toHaveAttribute('href', 'https://github.com/tonyzhaozh/act/blob/76cf30b4fed1d72dafbc3e1c270c0839d57e8bcf/imitate_episodes.py');
    await expect(page.locator('#ref-act-reference-2023')).toContainText('imitate_episodes.py');
    await page.locator('#ref-act-reference-2023').scrollIntoViewIfNeeded();
    await page.screenshot({ caret: 'initial', path: join(dir, `act-${viewport.width}-reference.png`) });
    const example = page.locator('p').filter({ hasText: 'For an illustrative scalar example' });
    await expect(example).toContainText('after selection');
    await expect(example).toContainText('9.93333444');
    await example.scrollIntoViewIfNeeded();
    await page.screenshot({ caret: 'initial', path: join(dir, `act-${viewport.width}-numeric.png`) });
    const latency = page.locator('p').filter({ hasText: 'The RTC experiment used π0.5' });
    await expect(latency).toContainText('76 ms for the baselines and 97 ms for RTC');
    await expect(latency).toContainText('an additional 100 or 200 ms');
    await expect(latency).toContainText('six tasks, ten episodes per task');
    await latency.scrollIntoViewIfNeeded();
    await page.screenshot({ caret: 'initial', path: join(dir, `act-${viewport.width}-latency.png`) });
    const delays = page.getByRole('slider', { name: /Injected inference delay/ });
    await expect(delays).toHaveCount(1);
    await expect(delays.first()).toHaveValue('0');
    await delays.first().focus();
    await page.keyboard.press('End');
    await expect(delays.first()).toHaveValue('240');
    await expect(page.getByTestId('rtc-throughput-readout').first()).toHaveText('100%');
    await page.getByRole('button', { name: 'Reset', exact: true }).last().click();
    await expect(delays.first()).toHaveValue('0');
    await page.getByRole('radio', { name: '+100 ms, added to the existing model and network latency', exact: true }).check();
    await expect(delays).toHaveCount(2);
    await expect(delays.nth(1)).toHaveValue('100');
    await expect(page.getByTestId('te-throughput-readout').nth(1)).toHaveText('0%');
    await expect(page.getByText(/Keep added delay separate from total latency/)).toBeVisible();
    await page.screenshot({ caret: 'initial', path: join(dir, `act-${viewport.width}-toy-reveal.png`) });
    const blog = page.locator('#ref-pi-real-time-chunking-blog-2025');
    await expect(blog).toContainText('Real-Time Action Chunking with Large Models');
    await expect(blog).toContainText('Kevin Black');
    await expect(blog).toContainText('Manuel Y. Galliker');
    await expect(blog).toContainText('Sergey Levine');
    await expect(blog.getByRole('link').first()).toHaveAttribute('href', 'https://www.pi.website/research/real_time_chunking');
    await blog.scrollIntoViewIfNeeded();
    await page.screenshot({ caret: 'initial', path: join(dir, `act-${viewport.width}-blog-identity.png`) });
    await page.screenshot({ caret: 'initial', fullPage: true, path: join(dir, `act-${viewport.width}-full.png`) });
    const metrics = await page.evaluate(() => {
      const h = document.querySelector('h1')!;
      const p = [...document.querySelectorAll('p')].find(p => p.textContent?.startsWith('The pinned ACT reference'))!;
      const css = getComputedStyle(p), hs = getComputedStyle(h);
      return { width: innerWidth, scrollWidth: document.documentElement.scrollWidth,
        proseFamily: css.fontFamily, proseSize: css.fontSize, proseLineHeight: css.lineHeight,
        h1Family: hs.fontFamily, h1Size: hs.fontSize,
        katexErrors: document.querySelectorAll('.katex-error').length,
        sourceCount: document.querySelectorAll('[id^="ref-"]').length };
    });
    expect(metrics.scrollWidth).toBeLessThanOrEqual(viewport.width);
    expect(metrics.proseFamily).toContain('Newsreader');
    expect(metrics.h1Family.toLowerCase()).toContain('tektur');
    expect(metrics.katexErrors).toBe(0);
    expect(metrics.sourceCount).toBe(7);
    const axe = await new AxeBuilder({ page }).analyze();
    writeFileSync(join(dir, `act-${viewport.width}-metrics.json`), JSON.stringify({ viewport, metrics, errors, axeViolations: axe.violations, svgSha256: createHash('sha256').update(svg).digest('hex') }, null, 2));
    expect(errors).toEqual([]);
    expect(axe.violations).toEqual([]);
  });
}
