/**
 * Prose search: types and helpers around the build-time Pagefind index.
 *
 * The index is generated by scripts/build-search.ts (postbuild) into
 * out/pagefind/. At runtime the browser loads /pagefind/pagefind.js lazily,
 * on the first query, via createPagefindClient(). Everything else in this
 * file is pure and unit-tested.
 *
 * Structured-entity search (MiniSearch over methods, companies, datasets)
 * is the other half of this same stack: lib/structured-search.ts builds the
 * documents and the integrity check; scripts/build-search.ts emits
 * public/search-index.json after the Pagefind step. The SearchClient
 * interface and the results area in components/search/ remain the UI seams.
 */

import { foldGreekToAscii } from './greek-transliteration';

/** One rendered prose result. */
export type SearchHit = {
  /** Path of the matching page, e.g. "/manipulation/action-chunking/". */
  url: string;
  /** Page title with the site-name suffix stripped (falls back to the URL). */
  title: string;
  /** Match-context snippet; may contain <mark> highlight markup. */
  excerpt: string;
};

/** Minimal search backend contract. Pagefind satisfies it for prose. */
export interface SearchClient {
  search(query: string): Promise<SearchHit[]>;
}

/** Cap on rendered prose results. Pagefind ranks by relevance. */
export const RESULT_LIMIT = 20;

/**
 * The site-name tail Pagefind appends to result titles, taken from the
 * <title> template in app/layout.tsx ('%s - robot-wiki'). The two must stay
 * in lockstep, or every search result renders with a visible site-name
 * suffix.
 */
const SITE_TITLE_SUFFIX = ' - robot-wiki';

/* The subset of the Pagefind runtime API this app consumes. */
export interface PagefindResultData {
  url: string;
  meta?: { title?: string };
  excerpt?: string;
  content?: string;
}

export interface PagefindResult {
  data: () => Promise<PagefindResultData>;
}

export interface PagefindSearchResponse {
  results: PagefindResult[];
}

/**
 * The one tokenizer both sides of the genuineness check must use.
 *
 * Every non-alphanumeric character is a boundary, so "sim-to-real" and
 * "pi0.5" split the same way whether they arrive as a query or as page
 * content. Splitting the query on a narrower set than the content is what
 * silently discarded whole query classes twice: a hyphenated query
 * collapsed to "simtoreal" until the dash was added to the split set, and
 * the period then did the same thing to every version-numbered query
 * ("pi0.5" became "pi05", which can never prefix-match ["pi0", "5"]).
 *
 * Greek letters fold to their ASCII names so the wiki's Greek-lettered
 * model names match the spelling a reader types, matching the folding the
 * structured index applies (lib/greek-transliteration.ts).
 */
function tokenize(value: string): string[] {
  return foldGreekToAscii(value)
    .split(/[^\p{L}\p{N}]+/u)
    .filter(Boolean);
}

/**
 * Pagefind truncates terms it cannot find until something matches: the
 * garbage query "zzqqxx" returns a hit whose excerpt marks "Z.". Those
 * fallback hits are indistinguishable by score, and the excerpt window can
 * miss the real match entirely (for "covariate" Pagefind excerpted and
 * marked "co-training"), so the excerpt cannot arbitrate. The full page
 * content can: a hit is genuine only if every query token is a prefix of
 * some word in the page content (exact matches and the typeahead case,
 * e.g. "tempor" matching "temporal"). Hits without content are kept, since
 * we cannot disprove them.
 */
export function isGenuineHit(query: string, content: string): boolean {
  const tokens = tokenize(query);
  if (tokens.length === 0) return false;
  if (!content.trim()) return true;
  const words = tokenize(content);
  return tokens.every((token) =>
    words.some((word) => word.startsWith(token)),
  );
}

function stripSiteSuffix(rawTitle: string | undefined, url: string): string {
  const trimmed = rawTitle?.trim();
  if (!trimmed) return url;
  return trimmed.endsWith(SITE_TITLE_SUFFIX)
    ? trimmed.slice(0, -SITE_TITLE_SUFFIX.length)
    : trimmed;
}

/**
 * How strongly a result's own title answers the query. Two tiers, because
 * they mean different things to a reader: 2 is the page that is ABOUT the
 * query (its title carries the whole query phrase), 1 is a page whose title
 * touches every query term without being named for the phrase, 0 is a page
 * that merely mentions it in the body.
 *
 * Pagefind ships no title field and no ranking configuration, so without
 * this an article ties with every index page that lists it. Since the
 * non-article destinations were added to the index, the home page and a
 * domain landing legitimately mention every article they link, which made
 * "the mention outranks the page itself" the common case rather than an
 * edge one.
 */
export function titleWeight(query: string, title: string): number {
  const queryTokens = tokenize(query);
  if (queryTokens.length === 0) return 0;
  const titleTokens = tokenize(title);
  if (titleTokens.length === 0) return 0;

  const phrase = queryTokens.join(' ');
  if (titleTokens.join(' ').includes(phrase)) return 2;

  return queryTokens.every((token) =>
    titleTokens.some((word) => word.startsWith(token)),
  )
    ? 1
    : 0;
}

/**
 * Maps a raw Pagefind response to ranked, renderable hits.
 *
 * Order of operations is load-bearing. Every raw result is resolved and
 * tested for genuineness FIRST, and only the survivors are capped: capping
 * the raw list first threw away a genuine hit the index happened to rank
 * just past the cap while a truncation-fallback hit inside the cap took its
 * place, so the rendered count fell below the cap with nothing to show that
 * anything had been dropped.
 *
 * Ranking is a stable sort on the title weight alone, so Pagefind's own
 * relevance order survives intact within each tier.
 */
export async function toSearchHits(
  response: PagefindSearchResponse,
  query: string,
  limit: number = RESULT_LIMIT,
): Promise<SearchHit[]> {
  const data = await Promise.all(
    response.results.map((result) => result.data()),
  );
  return data
    .filter((entry) => isGenuineHit(query, entry.content ?? ''))
    .map((entry) => ({
      url: entry.url,
      title: stripSiteSuffix(entry.meta?.title, entry.url),
      excerpt: entry.excerpt ?? '',
    }))
    .map((hit, index) => ({ hit, index, weight: titleWeight(query, hit.title) }))
    .sort((a, b) => b.weight - a.weight || a.index - b.index)
    .slice(0, limit)
    .map((entry) => entry.hit);
}

/**
 * Latest-wins sequencing for overlapping searches. Each new query begins a
 * token; only the most recent token may apply its results, so a slow
 * response for an older query can never mix into newer results
 */
export function createRequestSequencer(): {
  begin(): number;
  isCurrent(token: number): boolean;
  invalidate(): void;
} {
  let latest = 0;
  return {
    begin() {
      latest += 1;
      return latest;
    },
    isCurrent(token: number) {
      return token === latest;
    },
    invalidate() {
      latest += 1;
    },
  };
}

/**
 * Loads the Pagefind runtime and adapts it to SearchClient.
 *
 * The import specifier must stay invisible to the bundler: pagefind.js is
 * emitted by the postbuild indexing step and does not exist when Next.js
 * bundles this module. Rejects when the index is unavailable (for example
 * under the dev server, which never serves out/).
 */
export async function createPagefindClient(): Promise<SearchClient> {
  const runtimeImport = new Function(
    'specifier',
    'return import(specifier)',
  ) as (specifier: string) => Promise<unknown>;
  const pagefind = (await runtimeImport('/pagefind/pagefind.js')) as {
    search: (query: string) => Promise<PagefindSearchResponse>;
  };
  return {
    async search(query: string) {
      const response = await pagefind.search(query);
      return toSearchHits(response, query);
    },
  };
}
