/**
 * Prose search: types and helpers around the build-time Pagefind index.
 *
 * The index is generated by scripts/build-search.ts (postbuild) into
 * out/pagefind/. At runtime the browser loads /pagefind/pagefind.js lazily,
 * on the first query, via createPagefindClient(). Everything else in this
 * file is pure and unit-tested.
 *
 * Structured-entity search (MiniSearch over methods, companies, datasets)
 * is the other half of this same stack: lib/structured-search.ts builds the
 * documents and the integrity check; scripts/build-search.ts emits
 * public/search-index.json after the Pagefind step. The SearchClient
 * interface and the results area in components/search/ remain the UI seams.
 */

/** One rendered prose result. */
export type SearchHit = {
  /** Path of the matching page, e.g. "/manipulation/action-chunking/". */
  url: string;
  /** Page title with the site-name suffix stripped (falls back to the URL). */
  title: string;
  /** Match-context snippet; may contain <mark> highlight markup. */
  excerpt: string;
};

/** Minimal search backend contract. Pagefind satisfies it for prose. */
export interface SearchClient {
  search(query: string): Promise<SearchHit[]>;
}

/** Cap on rendered prose results. Pagefind ranks by relevance. */
export const RESULT_LIMIT = 20;

/**
 * The site-name tail Pagefind appends to result titles, taken from the
 * <title> template in app/layout.tsx ('%s - robot-wiki'). The two must stay
 * in lockstep, or every search result renders with a visible site-name
 * suffix.
 */
const SITE_TITLE_SUFFIX = ' - robot-wiki';

/* The subset of the Pagefind runtime API this app consumes. */
export interface PagefindResultData {
  url: string;
  meta?: { title?: string };
  excerpt?: string;
  content?: string;
}

export interface PagefindResult {
  data: () => Promise<PagefindResultData>;
}

export interface PagefindSearchResponse {
  results: PagefindResult[];
}

function normalizeWord(word: string): string {
  return word.toLowerCase().replace(/[^\p{L}\p{N}]/gu, '');
}

function contentWords(content: string): string[] {
  return content
    .toLowerCase()
    .split(/[^\p{L}\p{N}]+/u)
    .filter(Boolean);
}

/**
 * Pagefind truncates terms it cannot find until something matches: the
 * garbage query "zzqqxx" returns a hit whose excerpt marks "Z.". Those
 * fallback hits are indistinguishable by score, and the excerpt window can
 * miss the real match entirely (for "covariate" Pagefind excerpted and
 * marked "co-training"), so the excerpt cannot arbitrate. The full page
 * content can: a hit is genuine only if every query token is a prefix of
 * some word in the page content (exact matches and the typeahead case,
 * e.g. "tempor" matching "temporal"). Hits without content are kept, since
 * we cannot disprove them.
 */
export function isGenuineHit(query: string, content: string): boolean {
  const tokens = query.split(/\s+/).map(normalizeWord).filter(Boolean);
  if (tokens.length === 0) return false;
  if (!content.trim()) return true;
  const words = contentWords(content);
  return tokens.every((token) => words.some((word) => word.startsWith(token)));
}

/** Maps a raw Pagefind response to ranked, renderable hits. */
export async function toSearchHits(
  response: PagefindSearchResponse,
  query: string,
  limit: number = RESULT_LIMIT,
): Promise<SearchHit[]> {
  const top = response.results.slice(0, limit);
  const data = await Promise.all(top.map((result) => result.data()));
  return data
    .filter((entry) => isGenuineHit(query, entry.content ?? ''))
    .map((entry) => {
      const rawTitle = entry.meta?.title?.trim();
      return {
        url: entry.url,
        title: rawTitle
          ? rawTitle.endsWith(SITE_TITLE_SUFFIX)
            ? rawTitle.slice(0, -SITE_TITLE_SUFFIX.length)
            : rawTitle
          : entry.url,
        excerpt: entry.excerpt ?? '',
      };
    });
}

/**
 * Latest-wins sequencing for overlapping searches. Each new query begins a
 * token; only the most recent token may apply its results, so a slow
 * response for an older query can never mix into newer results
 * (VAL-SEARCH-011).
 */
export function createRequestSequencer(): {
  begin(): number;
  isCurrent(token: number): boolean;
  invalidate(): void;
} {
  let latest = 0;
  return {
    begin() {
      latest += 1;
      return latest;
    },
    isCurrent(token: number) {
      return token === latest;
    },
    invalidate() {
      latest += 1;
    },
  };
}

/**
 * Loads the Pagefind runtime and adapts it to SearchClient.
 *
 * The import specifier must stay invisible to the bundler: pagefind.js is
 * emitted by the postbuild indexing step and does not exist when Next.js
 * bundles this module. Rejects when the index is unavailable (for example
 * under the dev server, which never serves out/).
 */
export async function createPagefindClient(): Promise<SearchClient> {
  const runtimeImport = new Function(
    'specifier',
    'return import(specifier)',
  ) as (specifier: string) => Promise<unknown>;
  const pagefind = (await runtimeImport('/pagefind/pagefind.js')) as {
    search: (query: string) => Promise<PagefindSearchResponse>;
  };
  return {
    async search(query: string) {
      const response = await pagefind.search(query);
      return toSearchHits(response, query);
    },
  };
}
