/** Compile the two fixed scene relations once; the client ships markup, not the KaTeX renderer. */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import katex from 'katex';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export const equations = {
  kalman: String.raw`\hat{x}_k = \hat{x}_k^{-} + K\bigl(z-\hat{x}_k^{-}\bigr)`,
  diffusion: String.raw`a \sim p(a \mid o)`,
} as const;

export function generatedEquations(): string {
  return `/** Generated by scripts/generate-motion-equations.ts. Keep equations typeset. */\nexport const SCENE_EQUATIONS = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(equations).map(([key, tex]) => [
        key,
        { tex, html: katex.renderToString(tex, { output: 'htmlAndMathml', throwOnError: true }) },
      ]),
    ),
    null,
    2,
  )} as const;\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(join(root, 'lib/motion-equations.ts'), generatedEquations());
}
