/** Compile the two fixed scene relations once; the client ships markup, not the KaTeX renderer. */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import katex from 'katex';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export const equations = {
  kalman: String.raw`\hat{x}_k = \hat{x}_k^{-} + K\bigl(z-\hat{x}_k^{-}\bigr)`,
  diffusion: String.raw`a \sim p(a \mid o)`,
} as const;

/**
 * Single glyphs for scenes that move a relation glyph by glyph. Each one is
 * typeset alone, so its markup carries no spacing; the scene lays the glyphs
 * out from KaTeX's own advance widths. Each keeps its MathML layer even though
 * the stage is hidden from assistive technology: the article equation sweep
 * (VAL-B2-ART-007) holds every `.katex` root on a page to MathML plus a TeX
 * annotation, and KaTeX's stylesheet clips that layer, so the layout is unchanged.
 */
export const glyphs = {
  a: 'a',
  sim: String.raw`\sim`,
  p: 'p',
  lparen: '(',
  mid: String.raw`\mid`,
  o: 'o',
  rparen: ')',
} as const;

export function generatedEquations(): string {
  return `/** Generated by scripts/generate-motion-equations.ts. Keep equations typeset. */\nexport const SCENE_EQUATIONS = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(equations).map(([key, tex]) => [
        key,
        { tex, html: katex.renderToString(tex, { output: 'htmlAndMathml', throwOnError: true }) },
      ]),
    ),
    null,
    2,
  )} as const;\n\nexport const SCENE_GLYPHS = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(glyphs).map(([key, tex]) => [
        key,
        { tex, html: katex.renderToString(tex, { output: 'htmlAndMathml', throwOnError: true }) },
      ]),
    ),
    null,
    2,
  )} as const;\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(join(root, 'lib/motion-equations.ts'), generatedEquations());
}
