/**
 * Generated Open Graph asset prune.
 *
 * Removes only Finder-style sync-conflict duplicates under public/og. The
 * canonical tree is regenerated by `npm run generate:og-cards`; adjacent
 * public assets and repository-root files are intentionally outside scope.
 */
import { join } from 'node:path';
import { pruneGeneratedOgShadows } from '../lib/generated-og-shadows.ts';

const root = join(import.meta.dirname, '..');
const pruned = await pruneGeneratedOgShadows(root);

console.log(
  pruned.length > 0
    ? `prune-generated-og-shadows: OK (removed ${pruned.join(', ')})`
    : 'prune-generated-og-shadows: OK (nothing to remove)',
);
