import { describe, expect, it } from 'vitest';
import {
  buildNavFixture,
  scanSidebarDocument,
  serializeNavFixture,
  type SidebarScan,
} from '@/lib/nav-fixture';
import { PUBLIC_IDENTITY } from '@/lib/identity';

/**
 * Pure derivation/ordering logic for the nav accessible-name fixture
 * (tests/fixtures/nav-accessible-names.json), regenerated by
 * scripts/regen-nav-fixture.ts from the built static export.
 *
 * The derivation mirrors how the export actually renders: out/index.html
 * has every taxonomy group collapsed (buttons only), while each
 * out/<domain>/index.html server-renders its own group expanded. The
 * canonical order is the one tests/e2e/design-chrome.spec.ts observes
 * after expanding every section: brand link, then each group in the
 * order the root page's buttons list them, then the top-level entries.
 */

type Link = [href: string, name: string];

const TOP_LEVEL: Link[] = [
  ['/a-z/', 'A-Z Index'],
  ['/market-map/', 'Market Map'],
  ['/playground/', 'Playground'],
  ['/glossary/', 'Glossary'],
  ['/credits/', 'Credits'],
];

/** Sidebar markup shaped like the real export (attribute order included). */
function sidebarHtml(opts: {
  buttons: string[];
  groups?: Array<{ id: string; links: Link[] }>;
  topLevel?: Link[];
  brandCurrent?: boolean;
}): string {
  const { buttons, groups = [], topLevel = TOP_LEVEL, brandCurrent = false } = opts;
  const groupHtml = buttons
    .map((id) => {
      const group = groups.find((g) => g.id === id);
      const expanded = group
        ? `<ul id="${group.id}" class="mt-0.5 mb-1.5 flex flex-col gap-0.5">${group.links
            .map(
              ([href, name]) =>
                `<li><a class="relative block rounded-sm py-1 pl-7 pr-2 text-[13px] leading-snug transition-colors" href="${href}">${name}</a></li>`,
            )
            .join('')}</ul>`
        : '';
      return `<li><button type="button" aria-expanded="${group ? 'true' : 'false'}" aria-controls="${id}" class="flex w-full items-center gap-1.5"><span>Group</span></button>${expanded}</li>`;
    })
    .join('');
  return `<html><body>
    <aside data-pagefind-ignore="true" class="hidden w-72 shrink-0 border-r border-border lg:block">
      <div class="sticky top-0 flex h-dvh flex-col gap-5 overflow-y-auto px-3 py-5">
        <a ${brandCurrent ? 'aria-current="page" ' : ''}class="px-2 font-mono text-sm" href="/">Robot Wiki</a>
        <form role="search" aria-label="Site search"><input type="search" /></form>
        <nav aria-label="Robot Wiki taxonomy">
          <ul class="flex flex-col gap-0.5">${groupHtml}</ul>
          <ul class="mt-3 flex flex-col gap-0.5 border-t border-border pt-3">${topLevel
            .map(
              ([href, name]) =>
                `<li><a class="relative block rounded-sm px-2 py-1.5" href="${href}">${name}</a></li>`,
            )
            .join('')}</ul>
        </nav>
      </div>
    </aside>
    <main id="main-content"></main>
  </body></html>`;
}

function scan(html: string): SidebarScan {
  return scanSidebarDocument(new DOMParser().parseFromString(html, 'text/html'));
}

const DOMAIN_BUTTONS = [
  'sidebar-group-manipulation',
  'sidebar-group-frontier',
  'sidebar-group-adjacent',
];

function rootHtml(buttons = DOMAIN_BUTTONS): string {
  return sidebarHtml({ buttons });
}

function domainHtml(domain: string, links: Link[], buttons = DOMAIN_BUTTONS): string {
  return sidebarHtml({
    buttons,
    groups: [{ id: `sidebar-group-${domain}`, links }],
  });
}

const MANIPULATION: Link[] = [
  ['/manipulation/', 'Domain overview'],
  ['/manipulation/bc-foundations/', 'Behavior Cloning Foundations'],
  ['/manipulation/action-chunking/', 'Action Chunking (ACT and ALOHA)'],
];

const FRONTIER: Link[] = [
  ['/frontier/', 'Domain overview'],
  ['/frontier/reliability-gap/', 'The Reliability Gap'],
];

const ADJACENT: Link[] = [
  ['/adjacent/', 'Domain overview'],
  ['/adjacent/surgical/', 'Surgical Robotics'],
];

/** All-domain input with the caller's array deliberately NOT in button order. */
function assembledFixture() {
  const root = scan(rootHtml());
  return buildNavFixture(root, [
    { domain: 'adjacent', scan: scan(domainHtml('adjacent', ADJACENT)) },
    { domain: 'frontier', scan: scan(domainHtml('frontier', FRONTIER)) },
    { domain: 'manipulation', scan: scan(domainHtml('manipulation', MANIPULATION)) },
  ]);
}

describe('scanSidebarDocument', () => {
  it('extracts brand, button order, expanded groups, and top-level from a domain page', () => {
    const result = scan(domainHtml('manipulation', MANIPULATION));
    expect(result.brand).toEqual({ href: '/', name: PUBLIC_IDENTITY });
    expect(result.groupOrder).toEqual(DOMAIN_BUTTONS);
    expect(result.groups).toHaveLength(1);
    expect(result.groups[0]).toEqual({
      id: 'sidebar-group-manipulation',
      links: MANIPULATION.map(([href, name]) => ({ href, name })),
    });
    expect(result.topLevel).toEqual(TOP_LEVEL.map(([href, name]) => ({ href, name })));
  });

  it('reports zero groups when every section is collapsed (the root export)', () => {
    expect(scan(rootHtml()).groups).toEqual([]);
  });

  it('normalizes whitespace in accessible names', () => {
    const html = sidebarHtml({
      buttons: ['sidebar-group-manipulation'],
      groups: [
        {
          id: 'sidebar-group-manipulation',
          links: [['/manipulation/', 'Domain\u00a0\u00a0 overview\n']],
        },
      ],
    });
    expect(scan(html).groups[0].links[0].name).toBe('Domain overview');
  });

  it('ignores the aria-current marker span inside the active link', () => {
    // The active link renders an empty aria-hidden span before its text;
    // an accessible-name derivation must not pick up any of it.
    const html = domainHtml('manipulation', MANIPULATION).replace(
      'href="/manipulation/">Domain overview',
      'aria-current="page" href="/manipulation/"><span aria-hidden="true" class="absolute left-0 top-0 h-full border-l-2 border-accent"></span>Domain overview',
    );
    expect(scan(html).groups[0].links[0]).toEqual({
      href: '/manipulation/',
      name: 'Domain overview',
    });
  });

  it('throws when the page has no sidebar aside', () => {
    expect(() => scan('<html><body><main></main></body></html>')).toThrow(
      /no <aside> sidebar/,
    );
  });

  it('throws when the page has more than one aside', () => {
    const html = rootHtml().replace(
      '<main id="main-content"></main>',
      '<main id="main-content"><aside></aside></main>',
    );
    expect(() => scan(html)).toThrow(/aside/);
  });

  it('throws when the aside has no brand link to "/"', () => {
    expect(() => scan(rootHtml().replace('href="/"', 'href="/somewhere/"'))).toThrow(
      /brand link/,
    );
  });

  it('throws when a link renders an empty accessible name', () => {
    const html = sidebarHtml({
      buttons: ['sidebar-group-manipulation'],
      groups: [{ id: 'sidebar-group-manipulation', links: [['/manipulation/', '   ']] }],
    });
    expect(() => scan(html)).toThrow(/empty accessible name/);
  });
});

describe('buildNavFixture', () => {
  it('assembles canonical order: brand, groups in root-button order, top-level', () => {
    const fixture = assembledFixture();
    expect(fixture.links.map((l) => l.href)).toEqual([
      '/',
      ...MANIPULATION.map(([href]) => href),
      ...FRONTIER.map(([href]) => href),
      ...ADJACENT.map(([href]) => href),
      ...TOP_LEVEL.map(([href]) => href),
    ]);
    expect(fixture.links[0]).toEqual({ href: '/', name: PUBLIC_IDENTITY });
    expect(fixture.linkCount).toBe(fixture.links.length);
    expect(fixture.linkCount).toBe(1 + 3 + 2 + 2 + 5);
  });

  it('carries the capture metadata the committed fixture documents', () => {
    const fixture = assembledFixture();
    expect(fixture.capturedFrom).toBe('static export on :3201, sidebar sections expanded');
    expect(fixture.route).toBe('/');
    expect(fixture.viewport).toEqual([1440, 900]);
  });

  it('throws when the root export unexpectedly has an expanded group', () => {
    const root = scan(
      sidebarHtml({
        buttons: DOMAIN_BUTTONS,
        groups: [{ id: 'sidebar-group-manipulation', links: MANIPULATION }],
      }),
    );
    const domains = [
      { domain: 'adjacent', scan: scan(domainHtml('adjacent', ADJACENT)) },
      { domain: 'frontier', scan: scan(domainHtml('frontier', FRONTIER)) },
      { domain: 'manipulation', scan: scan(domainHtml('manipulation', MANIPULATION)) },
    ];
    expect(() => buildNavFixture(root, domains)).toThrow(/collapsed/);
  });

  it('throws when a root button has no matching expanded group', () => {
    const root = scan(rootHtml());
    const partial = [
      { domain: 'manipulation', scan: scan(domainHtml('manipulation', MANIPULATION)) },
    ];
    expect(() => buildNavFixture(root, partial)).toThrow(/sidebar-group-frontier/);
  });

  it('throws when a domain page expanded the wrong group', () => {
    const root = scan(rootHtml());
    const wrongLast = [
      { domain: 'adjacent', scan: scan(domainHtml('adjacent', ADJACENT)) },
      { domain: 'frontier', scan: scan(domainHtml('frontier', FRONTIER)) },
      // Position 3 should expand sidebar-group-manipulation (the third
      // root button); this scan expanded frontier's group instead.
      {
        domain: 'manipulation',
        scan: scan(
          sidebarHtml({
            buttons: DOMAIN_BUTTONS,
            groups: [{ id: 'sidebar-group-frontier', links: MANIPULATION }],
          }),
        ),
      },
    ];
    expect(() => buildNavFixture(root, wrongLast)).toThrow(/does not match/);
  });

  it('throws when a group does not start with its domain overview link', () => {
    const root = scan(rootHtml());
    const noOverview = [
      { domain: 'adjacent', scan: scan(domainHtml('adjacent', ADJACENT)) },
      { domain: 'frontier', scan: scan(domainHtml('frontier', FRONTIER)) },
      {
        domain: 'manipulation',
        scan: scan(domainHtml('manipulation', MANIPULATION.slice(1))),
      },
    ];
    expect(() => buildNavFixture(root, noOverview)).toThrow(/overview/);
  });

  it('throws when a module link escapes its own domain', () => {
    const root = scan(rootHtml());
    const escaped = [
      { domain: 'adjacent', scan: scan(domainHtml('adjacent', ADJACENT)) },
      { domain: 'frontier', scan: scan(domainHtml('frontier', FRONTIER)) },
      {
        domain: 'manipulation',
        scan: scan(
          domainHtml('manipulation', [
            ...MANIPULATION,
            ['/frontier/dexterity/', 'Dexterity'],
          ]),
        ),
      },
    ];
    expect(() => buildNavFixture(root, escaped)).toThrow(/escape their domain/);
  });

  it('throws on duplicate hrefs in the assembled fixture', () => {
    const root = scan(rootHtml());
    const dup = [
      { domain: 'adjacent', scan: scan(domainHtml('adjacent', ADJACENT)) },
      {
        domain: 'frontier',
        scan: scan(
          domainHtml('frontier', [
            ...FRONTIER,
            ['/frontier/reliability-gap/', 'The Reliability Gap (again)'],
          ]),
        ),
      },
      { domain: 'manipulation', scan: scan(domainHtml('manipulation', MANIPULATION)) },
    ];
    expect(() => buildNavFixture(root, dup)).toThrow(/duplicate/);
  });
});

describe('serializeNavFixture', () => {
  it('serializes with the committed fixture format: 2-space indent, key order, one trailing newline', () => {
    const json = serializeNavFixture(assembledFixture());
    expect(json.endsWith('\n')).toBe(true);
    expect(json.endsWith('\n\n')).toBe(false);
    const parsed = JSON.parse(json);
    expect(parsed).toEqual(assembledFixture());
    // Key order is part of byte identity with the committed fixture.
    expect(Object.keys(parsed)).toEqual([
      'capturedFrom',
      'route',
      'viewport',
      'linkCount',
      'links',
    ]);
    expect(Object.keys(parsed.links[0])).toEqual(['href', 'name']);
  });
});
