import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import pkg from '@/package.json';

// Guards the scaffold contract: critical dependencies stay exactly pinned
// (no caret/tilde ranges) and the required npm scripts exist.
describe('scaffold dependency pins', () => {
  const allDeps = { ...pkg.dependencies, ...pkg.devDependencies } as Record<
    string,
    string
  >;

  it('pins exact versions for every declared dependency', () => {
    // Allows plain exact pins ("16.3.0") and exact npm aliases
    // ("npm:typescript@6.0.3", used for the typescript-eslint TS 6 bridge).
    const exactPin = /^(npm:[a-z0-9@/.-]+@)?\d+\.\d+\.\d+$/;
    for (const [name, version] of Object.entries(allDeps)) {
      expect(version, `${name} must be pinned exactly`).toMatch(exactPin);
    }
  });

  it('pins the verified core stack from the architecture', () => {
    expect(allDeps.next).toBe('16.3.0');
    expect(allDeps['@next/mdx']).toBe('16.3.0');
    expect(allDeps.react).toMatch(/^19\./);
    expect(allDeps['react-dom']).toMatch(/^19\./);
    expect(allDeps.typescript).toBe('7.0.2');
    expect(allDeps.tailwindcss).toBe('4.3.3');
    expect(allDeps['@tailwindcss/postcss']).toBe('4.3.3');
    expect(allDeps['@react-three/fiber']).toBe('9.7.0');
    expect(allDeps['@react-three/drei']).toBe('10.7.8');
    expect(allDeps.three).toBe('0.185.1');
    expect(allDeps['urdf-loader']).toBe('0.13.1');
    expect(allDeps.motion).toBe('13.0.0');
    expect(allDeps.recharts).toBe('3.10.1');
    expect(allDeps.d3).toBe('7.9.0');
    expect(allDeps.pagefind).toBe('1.5.2');
    expect(allDeps.minisearch).toBe('7.2.0');
    expect(allDeps.katex).toBe('0.18.1');
    expect(allDeps.zod).toMatch(/^3\./);
    expect(allDeps.vitest).toBe('4.1.10');
    expect(allDeps['@playwright/test']).toBe('1.62.1');
    expect(allDeps['@axe-core/playwright']).toBe('4.12.1');
  });
});

describe('scaffold npm scripts', () => {
  it.each([
    'dev',
    'build',
    'typecheck',
    'lint',
    'test',
    'test:e2e',
    'validate:content',
  ])('defines the "%s" script', (script) => {
    expect(pkg.scripts).toHaveProperty(script);
  });
});

// Guards the environment-trap wiring: the bare dev command must stay inside
// the mission port range (3200-3299; 3000 and 3100 are off-limits), and the
// sync-conflict prune must run before every typecheck and every build, the
// generated OG tree must be cleaned before builds and standalone regeneration,
// and the export prune must stay wired into postbuild before search indexing.
describe('environment-trap script wiring', () => {
  it('pins the dev server to port 3200 so the bare command cannot leave the mission range', () => {
    expect(pkg.scripts.dev).toBe('next dev -p 3200');
  });

  it('prunes sync-conflict duplicates from the .next type dirs before every typecheck', () => {
    // npm runs pre<typecheck> automatically ahead of `typecheck`.
    expect(pkg.scripts.pretypecheck).toBe(
      'node scripts/prune-next-type-duplicates.ts',
    );
    expect(pkg.scripts.typecheck).toBe('next typegen && tsc --noEmit');
    expect(
      existsSync(
        join(import.meta.dirname, '../../scripts/prune-next-type-duplicates.ts'),
      ),
    ).toBe(true);
  });

  it('prunes sync-conflict duplicates from the .next type dirs before every build', () => {
    // npm runs pre<build> automatically ahead of `build`. The prune must
    // sit ahead of validate:content and the first `next build`: the build
    // type-checks .next/dev/types, which it never regenerates, so an
    // iCloud "routes.d 4.ts" ghost there fails `npm run build` with a
    // duplicate-identifier error that reads like an app type error
    // (measured 2026-08-23; .next/types is regenerated by the build,
    // .next/dev/types is not, and tsconfig includes both).
    expect(pkg.scripts.prebuild).toBe(
      'node scripts/prune-next-type-duplicates.ts && node scripts/prune-generated-og-shadows.ts && npm run validate:content',
    );
  });

  it('prunes only generated OG sync shadows immediately before every card generation path', () => {
    expect(pkg.scripts['pregenerate:og-cards']).toBe(
      'node scripts/prune-generated-og-shadows.ts',
    );
    expect(pkg.scripts['generate:og-cards']).toBe(
      'node scripts/generate-og-cards.ts',
    );
    expect(pkg.scripts.postbuild).toMatch(
      /npm run generate:og-cards$/,
    );
    expect(pkg.scripts.postbuild).not.toContain(
      'node scripts/generate-og-cards.ts',
    );
    expect(
      existsSync(
        join(import.meta.dirname, '../../scripts/prune-generated-og-shadows.ts'),
      ),
    ).toBe(true);
  });

  it('keeps the export prune wired into postbuild ahead of search indexing', () => {
    // The 404-guard patch sits between them (pre-hydration guard before the
    // Pagefind index sees the 404 document); ordering of all three matters.
    expect(pkg.scripts.postbuild).toMatch(
      /prune-export-artifacts\.ts && node scripts\/patch-404-guard\.ts && node scripts\/build-search\.ts/,
    );
  });
});
